
import type { Product, Category, Order, Review, BlogPost } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || 'https://picsum.photos/seed/default/600/600';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics' },
  { id: '2', name: 'Apparel', slug: 'apparel' },
  { id: '3', name: 'Home Goods', slug: 'home-goods' },
  { id: '4', name: 'Books', slug: 'books' },
  { id: '5', name: 'Toys & Games', slug: 'toys-games' },
  { id: '6', name: 'Sports', slug: 'sports' },
  { id: '7', name: 'Beauty', slug: 'beauty' },
  { id: '8', name: 'Automotive', slug: 'automotive' },
  { id: 'cat_men', name: 'Men', slug: 'men', parentId: '2'},
  { id: 'cat_women', name: 'Women', slug: 'women', parentId: '2'},
];

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Immerse yourself in music with these high-fidelity wireless headphones. Featuring active noise-cancellation and a 30-hour battery life, they are perfect for travel, work, and leisure. The plush earcups provide all-day comfort.',
    longDescription: 'Experience industry-leading noise cancellation with our state-of-the-art headphones. Dual noise sensor technology, featuring two microphones on each earcup, captures ambient noise and passes the data to the HD Noise-Cancelling Processor QN1. Using a new algorithm, the processor then applies noise-cancelling processing in real time to a range of acoustic environments. With a 30-hour battery life, you’ll have enough power for even long trips away. And if you need to top up in a hurry, you can get 5 hours’ worth of charge in just 10 minutes with the optional AC adapter.',
    price: 18999,
    salePrice: 14999,
    categoryId: '1',
    images: [findImage('headphone1'), findImage('headphone2')],
    inventory: 150,
    sku: 'SAM-HDP-BLK-01',
    tags: ['audio', 'tech', 'headphones'],
    weight: 254, // in grams
    dimensions: '18 x 7.5 x 25 cm',
  },
  {
    id: 'prod_2',
    name: 'Smartwatch Series 8',
    slug: 'smartwatch-series-8',
    description: 'Stay connected and track your fitness with the new Smartwatch Series 8. It features a brighter always-on display, advanced health sensors, and a durable design. Monitor your heart rate, blood oxygen, and daily activity effortlessly.',
    longDescription: 'The Smartwatch Series 8 is your ultimate partner for a healthy life. It features advanced sensors for insights into your health, including a temperature sensor for cycle tracking, and a blood oxygen sensor. The Always-On Retina display is bright and easy to read, even in direct sunlight. With a crack-resistant front crystal, IP6X dust resistance, and a swimproof design, it’s built for durability.',
    price: 29999,
    categoryId: '1',
    images: [findImage('smartwatch1'), findImage('smartwatch2')],
    inventory: 200,
    sku: 'SAM-SWT-S8-GRY-01',
    tags: ['smartwatch', 'fitness', 'tech'],
    weight: 45,
    dimensions: '45 x 38 x 10.7 mm',
  },
  {
    id: 'prod_3',
    name: 'Classic Cotton T-Shirt',
    slug: 'classic-cotton-t-shirt',
    description: 'A wardrobe essential, this classic t-shirt is made from 100% premium soft cotton. Its timeless design and comfortable fit make it perfect for layering or wearing on its own. Available in a variety of colors.',
    longDescription: 'Crafted from high-quality, long-staple cotton, this t-shirt offers unparalleled softness and breathability. The fabric is pre-shrunk to ensure a consistent fit even after multiple washes. Featuring a classic crew neck, a modern tailored fit, and durable double-stitching on the seams, it’s a versatile piece that forms the foundation of any wardrobe.',
    price: 999,
    categoryId: 'cat_men',
    images: [findImage('tshirt1'), findImage('tshirt2')],
    inventory: 500,
    sku: 'SAM-TSH-MEN-WHT-M',
    tags: ['apparel', 't-shirt', 'basics'],
    weight: 180,
    dimensions: 'N/A',
  },
  {
    id: 'prod_4',
    name: 'Modern Leather Backpack',
    slug: 'modern-leather-backpack',
    description: 'Carry your essentials in style with this minimalist leather backpack. It features a padded laptop compartment, multiple pockets for organization, and comfortable shoulder straps. Ideal for daily commutes and weekend trips.',
    longDescription: 'Designed for the modern professional, this backpack is handcrafted from full-grain leather that develops a beautiful patina over time. The spacious main compartment includes a padded sleeve for laptops up to 15 inches, while exterior and interior pockets keep your accessories organized. The adjustable shoulder straps and a padded back panel ensure maximum comfort on the go.',
    price: 4999,
    categoryId: '2',
    images: [findImage('backpack1'), findImage('backpack2')],
    inventory: 80,
    sku: 'SAM-BAG-LTHR-BRN-01',
    tags: ['bags', 'leather', 'fashion'],
    weight: 1200,
    dimensions: '42 x 30 x 12 cm',
  },
  {
    id: 'prod_5',
    name: 'Automatic Espresso Machine',
    slug: 'automatic-espresso-machine',
    description: 'Become your own barista with this fully automatic espresso machine. It grinds, tamps, and brews delicious espresso, cappuccinos, and lattes at the touch of a button. The integrated milk frother creates creamy foam for perfect coffee drinks.',
    longDescription: 'Enjoy barista-quality coffee at home with this intuitive machine. The integrated conical burr grinder offers multiple settings to suit your bean type, while the Thermoblock heating system ensures optimal temperature control. The automatic milk frother creates rich, creamy foam for lattes and cappuccinos. A one-touch control panel with a digital display makes it easy to select your favorite drink.',
    price: 59999,
    categoryId: '3',
    images: [findImage('espresso1'), findImage('espresso2')],
    inventory: 50,
    sku: 'SAM-KITCH-ESP-01',
    tags: ['kitchen', 'coffee', 'home'],
    weight: 8500,
    dimensions: '35 x 25 x 42 cm',
  },
  {
    id: 'prod_6',
    name: 'Cozy Knit Throw Blanket',
    slug: 'cozy-knit-throw-blanket',
    description: 'Snuggle up with this incredibly soft and cozy knit throw blanket. Perfect for adding a touch of warmth and texture to your sofa or bed. Made from a durable and machine-washable acrylic blend.',
    longDescription: 'Woven from a premium, ultra-soft acrylic blend, this chunky knit blanket is perfect for all seasons. Its generous size makes it ideal for cuddling on the couch or as an extra layer on your bed. The classic cable-knit design adds a timeless touch of elegance and texture to any room. It is hypoallergenic and easy to care for, making it a practical and stylish addition to your home.',
    price: 1499,
    categoryId: '3',
    images: [findImage('blanket1'), findImage('blanket2')],
    inventory: 120,
    sku: 'SAM-HOME-BLK-GRY-01',
    tags: ['home decor', 'textiles', 'cozy'],
    dimensions: '127 x 152 cm',
  },
  {
    id: 'prod_7',
    name: 'The Art of Programming',
    slug: 'the-art-of-programming',
    description: 'A comprehensive guide to the fundamentals of computer programming. This book covers everything from basic syntax to advanced algorithms, making it an essential read for both beginners and experienced developers.',
    longDescription: 'Dive deep into the world of software development with this definitive guide. "The Art of Programming" provides clear explanations of core concepts, practical examples in multiple languages, and exercises to test your understanding. Topics include data structures, algorithms, object-oriented design, and software engineering principles. It’s an invaluable resource for students, self-taught programmers, and professionals looking to solidify their knowledge.',
    price: 1299,
    categoryId: '4',
    images: [findImage('book1'), findImage('book2')],
    inventory: 300,
    sku: 'SAM-BOOK-PROG-HC-01',
    tags: ['books', 'education', 'programming'],
    weight: 850,
  },
  {
    id: 'prod_8',
    name: 'Sci-Fi Bestseller: "Nebula\'s Dawn"',
    slug: 'sci-fi-bestseller-nebulas-dawn',
    description: 'Embark on an epic journey across the galaxy in this critically acclaimed sci-fi novel. "Nebula\'s Dawn" weaves a tale of adventure, discovery, and the indomitable human spirit. A must-read for fans of the genre.',
    longDescription: 'From award-winning author A.K. Sterling comes a spellbinding tale of interstellar exploration and ancient mysteries. When a deep-space probe discovers a signal from a supposedly dead star, a crew of explorers is sent to investigate. What they find will challenge their understanding of the universe and their place within it. A gripping story with unforgettable characters and mind-bending concepts.',
    price: 799,
    categoryId: '4',
    images: [findImage('book3'), findImage('book4')],
    inventory: 450,
    sku: 'SAM-BOOK-SCIFI-PB-01',
    tags: ['books', 'sci-fi', 'fiction'],
  },
];

export const orders: Order[] = [
  {
    id: 'ord_1',
    customerName: 'Alice Johnson',
    customerEmail: 'alice@example.com',
    items: [
      { id: 'item_1', productId: 'prod_1', productName: 'Wireless Noise-Cancelling Headphones', quantity: 1, price: 14999 },
      { id: 'item_2', productId: 'prod_7', productName: 'The Art of Programming', quantity: 1, price: 1299 },
    ],
    total: 16298,
    status: 'Shipped',
    createdAt: new Date('2023-10-26T10:00:00Z'),
  },
  {
    id: 'ord_2',
    customerName: 'Bob Smith',
    customerEmail: 'bob@example.com',
    items: [
      { id: 'item_3', productId: 'prod_3', productName: 'Classic Cotton T-Shirt', quantity: 3, price: 999 },
    ],
    total: 2997,
    status: 'Processing',
    createdAt: new Date('2023-10-28T14:30:00Z'),
  },
  {
    id: 'ord_3',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    items: [
      { id: 'item_4', productId: 'prod_5', productName: 'Automatic Espresso Machine', quantity: 1, price: 59999 },
    ],
    total: 59999,
    status: 'Delivered',
    createdAt: new Date('2023-10-20T09:00:00Z'),
  },
  {
    id: 'ord_4',
    customerName: 'Diana Prince',
    customerEmail: 'diana@example.com',
    items: [
      { id: 'item_5', productId: 'prod_2', productName: 'Smartwatch Series 8', quantity: 1, price: 29999 },
      { id: 'item_6', productId: 'prod_4', productName: 'Modern Leather Backpack', quantity: 1, price: 4999 },
    ],
    total: 34998,
    status: 'Pending',
    createdAt: new Date('2023-10-29T11:00:00Z'),
  },
];

export const reviews: Review[] = [
    {
        id: 'rev_1',
        productId: 'prod_1',
        authorName: 'Tech Guru',
        rating: 5,
        comment: 'Absolutely phenomenal sound quality and the noise cancellation is top-tier. Worth every penny!',
        status: 'Approved',
        createdAt: new Date('2023-10-27T10:00:00Z'),
    },
     {
        id: 'rev_2',
        productId: 'prod_1',
        authorName: 'Daily Commuter',
        rating: 4,
        comment: 'Great for my daily commute on the train. Comfortable for long periods, though the battery could be slightly better.',
        status: 'Approved',
        createdAt: new Date('2023-10-28T10:00:00Z'),
    },
     {
        id: 'rev_3',
        productId: 'prod_3',
        authorName: 'Sam',
        rating: 5,
        comment: 'This is the softest t-shirt I have ever owned. I bought one in every color. Highly recommend!',
        status: 'Pending',
        createdAt: new Date('2023-10-29T10:00:00Z'),
    },
     {
        id: 'rev_4',
        productId: 'prod_2',
        authorName: 'Fitness Fanatic',
        rating: 4,
        comment: 'The fitness tracking is very accurate. I wish it had more third-party app integrations, but overall a solid device for workouts.',
        status: 'Approved',
        createdAt: new Date('2023-10-25T10:00:00Z'),
    }
]

export const blogPosts: BlogPost[] = [
    {
        id: 'post_1',
        title: 'The Ultimate Guide to Choosing the Right Headphones',
        slug: 'ultimate-guide-to-choosing-headphones',
        author: 'John Doe',
        date: new Date('2023-10-15'),
        image: findImage('slider1'),
        excerpt: 'In a world saturated with audio gadgets, finding the perfect pair of headphones can be overwhelming. This guide will walk you through the key factors to consider, from sound quality to comfort and design.',
        content: 'Full content goes here...',
        tags: ['Tech', 'Audio', 'Guides'],
    },
    {
        id: 'post_2',
        title: '5 Ways to Style a Classic White T-Shirt',
        slug: '5-ways-to-style-a-classic-white-t-shirt',
        author: 'Jane Smith',
        date: new Date('2023-10-18'),
        image: findImage('slider2'),
        excerpt: 'The white t-shirt is a timeless wardrobe staple. Discover five creative and stylish ways to elevate this simple piece for any occasion, from casual outings to chic evening looks.',
        content: 'Full content goes here...',
        tags: ['Fashion', 'Style', 'Apparel'],
    },
     {
        id: 'post_3',
        title: 'Creating the Perfect Morning Routine with Smart Home Tech',
        slug: 'creating-the-perfect-morning-routine-with-smart-home-tech',
        author: 'Alex Johnson',
        date: new Date('2023-10-22'),
        image: findImage('slider3'),
        excerpt: 'Transform your mornings from chaotic to calm with the help of smart home technology. We explore how smartwatches, espresso machines, and other gadgets can help you start your day right.',
        content: 'Full content goes here...',
        tags: ['Home', 'Tech', 'Lifestyle'],
    },
]
